server:
  port: 8080
logging:
  level:
    nuclear.bot.core: TRACE
notification:
  level: INFO
spring:
  kafka:
    template:
      default-topic: parser-event
    consumer:
      bootstrap-servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: nuclear.bot.core.config.MessageAdapter
      group-id: core
      properties:
        key-class: java.lang.String
        value-class: nuclear.bot.core.dto.AgentMessage
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgresdb.postgresql.svc.cluster.local:5432/nuclear?useSSL=false
    username: pgadmin
    password: pgadmin
    driver-class-name: org.postgresql.Driver