CREATE TABLE USER_NOTIFICATION_INFO
(
    id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    CHAT_ID  VARCHAR(100) UNIQUE NOT NULL,
    IS_EVERY_MORNING BOOLEAN NOT NULL DEFAULT FALSE
);